import 'package:flutter_dotenv/flutter_dotenv.dart';

var host = dotenv.env['HOST'];

/// True only when Firebase.initializeApp() succeeded in main().
///
/// Firebase is provisioned for Android and web (firebase_options.dart and
/// android/app/google-services.json, generated by `flutterfire configure`).
/// It still fails to initialise on platforms that were not configured, such
/// as Windows desktop, or on a checkout missing the generated files. Every
/// Firebase path in UserService checks this flag first so the app keeps
/// running on the DummyJSON backend in those cases.
bool firebaseReady = false;
